name: Deploy frontend to GitHub Pages

on:
  push:
    branches: ["main"]
    paths:
      - "frontend/**"
      - ".github/workflows/deploy-frontend.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install
        working-directory: frontend
        run: npm ci

      - name: Build
        working-directory: frontend
        env:
          VITE_API_URL: ${{ vars.VITE_API_URL }}
          VITE_AUTH_API_URL: ${{ vars.VITE_AUTH_API_URL }}
          VITE_JOURNAL_API_URL: ${{ vars.VITE_JOURNAL_API_URL }}
        run: npm run build

      - name: Disable Jekyll
        run: touch frontend/dist/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: frontend/dist

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
